# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ haproxyctl_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - haproxyctl
    - haproxyctl-install
    - haproxyctl-install-dependencies

- name: create (checkout) directory
  ansible.builtin.file:
    path: /var/lib/ansible/haproxyctl/checkouts
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - haproxyctl
    - haproxyctl-checkout

- name: checkout repository
  ansible.builtin.git:
    repo: https://github.com/flores/haproxyctl.git
    dest: "{{ haproxyctl_checkout_path }}"
    force: true
  tags:
    - configuration
    - haproxyctl
    - haproxyctl-checkout

- name: install
  ansible.builtin.file:
    src: "{{ haproxyctl_checkout_path }}/haproxyctl"
    dest: "{{ haproxyctl_install_path }}/haproxyctl"
    state: link
    force: true
  tags:
    - configuration
    - haproxyctl
    - haproxyctl-install
